# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

        environment:
          HOST: mongodb+srv://rfeldman:reed@cluster0-y27fx.mongodb.net/test?retryWrites=true&w=majorit
          BOT_ID: 349026222344891
          DB: expenses
          ACCESS_KEY: AKIAXSBKOXMFANOUZKH5
          SECRET_KEY: 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
          REGION: us-east-1





    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run app
          command: |
            . venv/bin/activate
            python python/main_rsa.py

      - store_artifacts:
          path: test-reports
          destination: test-reports
